# Numpy

Его нужно знать совсем немного. Если вкратце, Numpy - штука для привычных нам массивов и матриц, только очень-очень быстро работающая.

Загляните [в этот туториал](http://cs231n.github.io/python-numpy-tutorial/). Суперклассно, если вы все это знаете. Если нет, - ничего страшного, вам нужно совсем немного:

###### Создание и размер

In [1]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
a.shape

(2, 3)

###### Простые действия

In [3]:
a + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [4]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

###### Индексация

In [5]:
a[0, 0]

1

In [6]:
a[0, 2]

3

In [7]:
a[1, 1]

5

In [8]:
a[:, 0]

array([1, 4])

In [9]:
a[:, 1]

array([2, 5])

In [10]:
a[:, 2]

array([3, 6])

In [11]:
a[0, :]

array([1, 2, 3])

In [12]:
a[1, :]

array([4, 5, 6])

###### Комбинации

In [13]:
b = np.array([[7,8,9], [3,4,5]])

In [14]:
print(a, '\n\n', b)

[[1 2 3]
 [4 5 6]] 

 [[7 8 9]
 [3 4 5]]


In [15]:
np.hstack((a,b))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 3, 4, 5]])

In [16]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 4, 5]])

И, в общем-то, все. В дальнейшем будем работать с более высокоуровневым фреймворком Pandas. Но у того под капотом лежит как раз Numpy, поэтому кое-какие основы знать необходимо.